language: minimal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6

before_script:
  - FC=gfortran-6 cmake .
  - cmake --build . --parallel
script:
  - ctest
